// Code generated by chiptool; DO NOT EDIT.

package ast2600

// Peripheral base addresses
const (
    // SCU_BASE System Control Unit
    SCU_BASE = 0x1e6e2000
    // UART5_BASE UART5 (ARM console, 16550-compatible)
    UART5_BASE = 0x1e784000
    // TIMER_BASE Timer Controller 1
    TIMER_BASE = 0x1e782000
    // GIC_BASE Generic Interrupt Controller distributor base (GICD=BASE+0x1000, GICC=BASE+0x2000)
    GIC_BASE = 0x40460000
)

// IRQ numbers
const (
    // UART5_IRQ UART5 (GIC SPI 8)
    UART5_IRQ = 40
    // HACE_IRQ Hash and Crypto Engine / TRNG (GIC SPI 4)
    HACE_IRQ = 36
    // TIMER1_IRQ Timer 1 overflow (GIC SPI 16)
    TIMER1_IRQ = 48
    // TIMER2_IRQ Timer 2 overflow (GIC SPI 17)
    TIMER2_IRQ = 49
    // WDT_IRQ Watchdog timer alarm (GIC SPI 24)
    WDT_IRQ = 56
)
