// Code generated by chiptool; DO NOT EDIT.

package ast2600

import "github.com/usbarmory/tamago/internal/reg"

// Scu AST2600 System Control Unit.
type Scu struct {
    Base uintptr
}

// ReadPROTECTIONKEY reads SCU000 Protection Key Register. Write 0x1688A8A8 to unlock, any other value to lock. Read-back 0x1=unlocked.
func (p *Scu) ReadPROTECTIONKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WritePROTECTIONKEY writes SCU000 Protection Key Register. Write 0x1688A8A8 to unlock, any other value to lock. Read-back 0x1=unlocked.
func (p *Scu) WritePROTECTIONKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadREVID reads SCU004 Silicon Revision ID Register. Bits[23:16]=HW revision (0x00=A0, 0x01=A1, 0x02=A2, 0x03=A3).
func (p *Scu) ReadREVID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// ReadREVID2 reads SCU014 Silicon Revision ID Register 2. Bits[23:16]=secondary HW revision.
func (p *Scu) ReadREVID2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// ReadCLKSTOPSET1 reads SCU080 Clock Stop Control Register Set 1. Write 1 to stop clock. Use CLK_STOP_CLR1 to restart. Bit15=UART5CLK, Bit13=HACE/RNG clock.
func (p *Scu) ReadCLKSTOPSET1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteCLKSTOPSET1 writes SCU080 Clock Stop Control Register Set 1. Write 1 to stop clock. Use CLK_STOP_CLR1 to restart. Bit15=UART5CLK, Bit13=HACE/RNG clock.
func (p *Scu) WriteCLKSTOPSET1(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// WriteCLKSTOPCLR1 writes SCU084 Clock Stop Control Clear Register 1. Write 1 to clear (restart) the corresponding clock stop bit in SCU080.
func (p *Scu) WriteCLKSTOPCLR1(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadHWSTRAP1 reads SCU500 Hardware Strap 1 Register. Bits[10:8]=CPU frequency selection (000=1.2GHz, 001=1.6GHz, 100+=800MHz).
func (p *Scu) ReadHWSTRAP1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0500))
}

// ReadRNG1CTRL reads SCU520 RNG Unit 1 Control Register. Bit0=disable(0=enabled). New random value every ~1 µs.
func (p *Scu) ReadRNG1CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0520))
}

// WriteRNG1CTRL writes SCU520 RNG Unit 1 Control Register. Bit0=disable(0=enabled). New random value every ~1 µs.
func (p *Scu) WriteRNG1CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0520, uint32(val))
}

// ReadRNG1DATA reads SCU524 RNG Unit 1 Data Output. Read to get 32-bit random number. No ready flag; new value every 1 µs.
func (p *Scu) ReadRNG1DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0524))
}

// ReadRNG2CTRL reads SCU530 RNG Unit 2 Control Register. Bit31=data_valid(RO, cleared by reading RNG2_DATA). Bit0=disable(0=enabled).
func (p *Scu) ReadRNG2CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0530))
}

// WriteRNG2CTRL writes SCU530 RNG Unit 2 Control Register. Bit31=data_valid(RO, cleared by reading RNG2_DATA). Bit0=disable(0=enabled).
func (p *Scu) WriteRNG2CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0530, uint32(val))
}

// ReadRNG2DATA reads SCU534 RNG Unit 2 Data Output. Reading this register clears the data_valid bit (SCU530[31]).
func (p *Scu) ReadRNG2DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0534))
}

// ScuRevId SCU Silicon Revision ID Register fields.
const (
    // HWREV Hardware revision ID. 0x00=A0, 0x01=A1, 0x02=A2, 0x03=A3.
    ScuRevIdHWREVPos = 16
    ScuRevIdHWREVMsk = 0xff << 16
)

// ScuClkStop1 SCU Clock Stop Control Register 1 fields.
const (
    // HACE Hash and Crypto Engine (HACE) clock stop. 1=stopped, 0=running.
    ScuClkStop1HACEPos = 13
    ScuClkStop1HACEMsk = 0x1 << 13
    // UART5 UART5 clock stop. 0=running (default), 1=stopped.
    ScuClkStop1UART5Pos = 15
    ScuClkStop1UART5Msk = 0x1 << 15
)

// ScuHwStrap1 SCU Hardware Strap 1 register fields.
const (
    // CPUFREQSEL CPU frequency selection. 0b000/0b010=1.2GHz, 0b001/0b011=1.6GHz, 0b100+=800MHz.
    ScuHwStrap1CPUFREQSELPos = 8
    ScuHwStrap1CPUFREQSELMsk = 0x7 << 8
)

// ScuRngCtrl SCU RNG1 Control Register fields.
const (
    // DISABLE RNG disable control. 0=enabled (default), 1=disabled.
    ScuRngCtrlDISABLEPos = 0
    ScuRngCtrlDISABLEMsk = 0x1 << 0
)

// ScuRng2Ctrl SCU RNG2 Control Register fields.
const (
    // DATAVALID Random data valid flag (RO). Set by hardware when data is ready. Cleared by reading RNG2_DATA.
    ScuRng2CtrlDATAVALIDPos = 31
    ScuRng2CtrlDATAVALIDMsk = 0x1 << 31
    // DISABLE RNG disable control. 0=enabled (default), 1=disabled.
    ScuRng2CtrlDISABLEPos = 0
    ScuRng2CtrlDISABLEMsk = 0x1 << 0
)

