// Code generated by chiptool; DO NOT EDIT.

package ast2600

import "github.com/usbarmory/tamago/internal/reg"

// Timer AST2600 Timer Controller. 8 decrement timers; clock = PCLK or 1 MHz. Timer N at byte_offset (N-1)*0x10 (N=1..3), then 0x40+(N-4)*0x10 for N=4..8.
type Timer struct {
    Base uintptr
}

// ReadT1STATUS reads Timer 1 Counter Status Register. Current countdown value. Also writable to set initial value.
func (p *Timer) ReadT1STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteT1STATUS writes Timer 1 Counter Status Register. Current countdown value. Also writable to set initial value.
func (p *Timer) WriteT1STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadT1RELOAD reads Timer 1 Counter Reload Value. Loaded when counter reaches 0.
func (p *Timer) ReadT1RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteT1RELOAD writes Timer 1 Counter Reload Value. Loaded when counter reaches 0.
func (p *Timer) WriteT1RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadT1MATCH1 reads Timer 1 First Match Register. Set to 0xFFFFFFFF to disable match interrupt.
func (p *Timer) ReadT1MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteT1MATCH1 writes Timer 1 First Match Register. Set to 0xFFFFFFFF to disable match interrupt.
func (p *Timer) WriteT1MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadT1MATCH2 reads Timer 1 Second Match Register. Set to 0xFFFFFFFF to disable match interrupt.
func (p *Timer) ReadT1MATCH2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteT1MATCH2 writes Timer 1 Second Match Register. Set to 0xFFFFFFFF to disable match interrupt.
func (p *Timer) WriteT1MATCH2(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadT2STATUS reads Timer 2 Counter Status Register.
func (p *Timer) ReadT2STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteT2STATUS writes Timer 2 Counter Status Register.
func (p *Timer) WriteT2STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadT2RELOAD reads Timer 2 Counter Reload Value.
func (p *Timer) ReadT2RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteT2RELOAD writes Timer 2 Counter Reload Value.
func (p *Timer) WriteT2RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadT2MATCH1 reads Timer 2 First Match Register.
func (p *Timer) ReadT2MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteT2MATCH1 writes Timer 2 First Match Register.
func (p *Timer) WriteT2MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadT2MATCH2 reads Timer 2 Second Match Register.
func (p *Timer) ReadT2MATCH2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteT2MATCH2 writes Timer 2 Second Match Register.
func (p *Timer) WriteT2MATCH2(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadCTRL reads TMC30 Timer Control Register. 4 bits per timer (timer N at bit[4*(N-1)]): bit+0=enable, bit+1=1MHz_clock_sel, bit+2=overflow_irq_en, bit+3=wdt_reset_en. Write 1 to set; use CTRL_CLR to clear.
func (p *Timer) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCTRL writes TMC30 Timer Control Register. 4 bits per timer (timer N at bit[4*(N-1)]): bit+0=enable, bit+1=1MHz_clock_sel, bit+2=overflow_irq_en, bit+3=wdt_reset_en. Write 1 to set; use CTRL_CLR to clear.
func (p *Timer) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadIRQSTATUS reads TMC34 Timer Interrupt Status Register. Bit N-1 = Timer N overflow interrupt (write 1 to clear).
func (p *Timer) ReadIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteIRQSTATUS writes TMC34 Timer Interrupt Status Register. Bit N-1 = Timer N overflow interrupt (write 1 to clear).
func (p *Timer) WriteIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// WriteCTRLCLR writes TMC3C Timer Control Clear Register. Write 1 to clear corresponding bits in CTRL (TMC30). Used to disable/stop timers.
func (p *Timer) WriteCTRLCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// TimerCtrl Timer Control Register fields (4 bits per timer).
const (
    // T1EN Timer 1 enable. 1=running, 0=stopped.
    TimerCtrlT1ENPos = 0
    TimerCtrlT1ENMsk = 0x1 << 0
    // T11MHZ Timer 1 clock select. 0=PCLK, 1=1 MHz fixed clock.
    TimerCtrlT11MHZPos = 1
    TimerCtrlT11MHZMsk = 0x1 << 1
    // T1OVFIRQ Timer 1 overflow interrupt enable.
    TimerCtrlT1OVFIRQPos = 2
    TimerCtrlT1OVFIRQMsk = 0x1 << 2
    // T1WDTRST Timer 1 trigger watchdog reset on overflow.
    TimerCtrlT1WDTRSTPos = 3
    TimerCtrlT1WDTRSTMsk = 0x1 << 3
    // T2EN Timer 2 enable. 1=running, 0=stopped.
    TimerCtrlT2ENPos = 4
    TimerCtrlT2ENMsk = 0x1 << 4
    // T21MHZ Timer 2 clock select. 0=PCLK, 1=1 MHz fixed clock.
    TimerCtrlT21MHZPos = 5
    TimerCtrlT21MHZMsk = 0x1 << 5
    // T2OVFIRQ Timer 2 overflow interrupt enable.
    TimerCtrlT2OVFIRQPos = 6
    TimerCtrlT2OVFIRQMsk = 0x1 << 6
    // T2WDTRST Timer 2 trigger watchdog reset on overflow.
    TimerCtrlT2WDTRSTPos = 7
    TimerCtrlT2WDTRSTMsk = 0x1 << 7
)

