// Code generated by chiptool; DO NOT EDIT.

package ast2600

import "github.com/usbarmory/tamago/internal/reg"

// Uart 16550-compatible UART (AST2600 UART5 console).
type Uart struct {
    Base uintptr
}

// ReadRBR reads Receive Buffer Register (DLAB=0, read). Contains received byte.
func (p *Uart) ReadRBR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteTHR writes Transmitter Holding Register (DLAB=0, write). Write byte to transmit.
func (p *Uart) WriteTHR(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadIER reads Interrupt Enable Register (DLAB=0). Bit0=RxDataAvail, Bit1=TxEmpty, Bit2=RxLineStatus, Bit3=ModemStatus.
func (p *Uart) ReadIER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteIER writes Interrupt Enable Register (DLAB=0). Bit0=RxDataAvail, Bit1=TxEmpty, Bit2=RxLineStatus, Bit3=ModemStatus.
func (p *Uart) WriteIER(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// WriteFCR writes FIFO Control Register (write). Bit0=FIFO enable, Bit1=Rx FIFO reset, Bit2=Tx FIFO reset.
func (p *Uart) WriteFCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadIIR reads Interrupt Identity Register (read). Bit0=0 means interrupt pending. Bits[3:1]=interrupt type.
func (p *Uart) ReadIIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// ReadLCR reads Line Control Register. Bits[1:0]=word length(11=8bit), Bit2=stop bits, Bits[5:3]=parity, Bit7=DLAB.
func (p *Uart) ReadLCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteLCR writes Line Control Register. Bits[1:0]=word length(11=8bit), Bit2=stop bits, Bits[5:3]=parity, Bit7=DLAB.
func (p *Uart) WriteLCR(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMCR reads Modem Control Register.
func (p *Uart) ReadMCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMCR writes Modem Control Register.
func (p *Uart) WriteMCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadLSR reads Line Status Register. Bit0=RxDataReady, Bit5=TxHoldingEmpty(THR empty), Bit6=TxEmpty.
func (p *Uart) ReadLSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// UartLcr UART Line Control Register fields.
const (
    // WORDLEN Word length. 0b11=8 bits, 0b10=7 bits, 0b01=6 bits, 0b00=5 bits.
    UartLcrWORDLENPos = 0
    UartLcrWORDLENMsk = 0x3 << 0
    // STOPBITS Stop bits. 0=1 stop bit, 1=2 stop bits.
    UartLcrSTOPBITSPos = 2
    UartLcrSTOPBITSMsk = 0x1 << 2
    // PARITYEN Parity enable. 0=no parity, 1=parity enabled.
    UartLcrPARITYENPos = 3
    UartLcrPARITYENMsk = 0x1 << 3
    // DLAB Divisor Latch Access Bit. 1=access DLL/DLH baud rate divisors at offsets 0x00/0x04.
    UartLcrDLABPos = 7
    UartLcrDLABMsk = 0x1 << 7
)

// UartLsr UART Line Status Register fields.
const (
    // RXREADY Receive data ready. 1=data available in receive buffer.
    UartLsrRXREADYPos = 0
    UartLsrRXREADYMsk = 0x1 << 0
    // TXHOLDEMPTY Transmitter holding register empty. 1=THR is empty, safe to write next byte.
    UartLsrTXHOLDEMPTYPos = 5
    UartLsrTXHOLDEMPTYMsk = 0x1 << 5
    // TXEMPTY Transmitter empty. 1=both THR and shift register are empty.
    UartLsrTXEMPTYPos = 6
    UartLsrTXEMPTYMsk = 0x1 << 6
)

