// Code generated by chiptool; DO NOT EDIT.

package ast2500

// Peripheral base addresses
const (
    // SCU_BASE System Control Unit
    SCU_BASE = 0x1e6e2000
    // UART5_BASE UART5 (ARM console, 16550-compatible)
    UART5_BASE = 0x1e784000
    // TIMER_BASE Timer Controller (FTTMR010)
    TIMER_BASE = 0x1e782000
    // VIC_BASE Vectored Interrupt Controller (64 IRQs)
    VIC_BASE = 0x1e6c0000
)

// IRQ numbers
const (
    // UART5_IRQ UART5 (VIC IRQ 8)
    UART5_IRQ = 8
    // TIMER1_IRQ Timer 1 overflow (VIC IRQ 16)
    TIMER1_IRQ = 16
    // TIMER2_IRQ Timer 2 overflow (VIC IRQ 17)
    TIMER2_IRQ = 17
)
