// Code generated by chiptool; DO NOT EDIT.

package ast2500

import "github.com/usbarmory/tamago/internal/reg"

// Scu AST2500 System Control Unit.
type Scu struct {
    Base uintptr
}

// ReadPROTECTIONKEY reads SCU00 Protection Key. Write 0x1688A8A8 to unlock; any other value to lock.
func (p *Scu) ReadPROTECTIONKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WritePROTECTIONKEY writes SCU00 Protection Key. Write 0x1688A8A8 to unlock; any other value to lock.
func (p *Scu) WritePROTECTIONKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadSYSRSTCTRL1 reads SCU04 System Reset Control Register 1.
func (p *Scu) ReadSYSRSTCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteSYSRSTCTRL1 writes SCU04 System Reset Control Register 1.
func (p *Scu) WriteSYSRSTCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCLKSEL1 reads SCU08 Clock Selection Register 1.
func (p *Scu) ReadCLKSEL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCLKSEL1 writes SCU08 Clock Selection Register 1.
func (p *Scu) WriteCLKSEL1(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCLKSTOP1 reads SCU0C Clock Stop Control Register 1. Write 1 to stop a peripheral clock. Bit15=UART5, Bit13=HACE.
func (p *Scu) ReadCLKSTOP1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCLKSTOP1 writes SCU0C Clock Stop Control Register 1. Write 1 to stop a peripheral clock. Bit15=UART5, Bit13=HACE.
func (p *Scu) WriteCLKSTOP1(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadHWSTRAP reads SCU70 Hardware Strap Register. Bits[11:10]=DRAM size, bits[9:8]=DRAM config, bits[7:6]=CPU speed.
func (p *Scu) ReadHWSTRAP() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// ReadREVID reads SCU7C Silicon Revision ID Register. Bits[27:24]=chip generation, bits[23:16]=hardware revision.
func (p *Scu) ReadREVID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// ScuClkStop SCU0C Clock Stop Control Register 1.
const (
    // HACE HACE/RNG clock stop. 1=stopped.
    ScuClkStopHACEPos = 13
    ScuClkStopHACEMsk = 0x1 << 13
    // UART5 UART5 clock stop. 1=stopped.
    ScuClkStopUART5Pos = 15
    ScuClkStopUART5Msk = 0x1 << 15
)

// ScuRevId SCU7C Silicon Revision ID.
const (
    // HWREV Hardware revision. Bits[23:16]: hardware revision ID.
    ScuRevIdHWREVPos = 16
    ScuRevIdHWREVMsk = 0xff << 16
    // GEN Chip generation. Bits[27:24].
    ScuRevIdGENPos = 24
    ScuRevIdGENMsk = 0xf << 24
)

