// Code generated by chiptool; DO NOT EDIT.

package ast2500

import "github.com/usbarmory/tamago/internal/reg"

// Uart 16550-compatible UART (AST2500 UART5 console).
type Uart struct {
    Base uintptr
}

// ReadRBR reads Receive Buffer Register (DLAB=0, read).
func (p *Uart) ReadRBR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteTHR writes Transmitter Holding Register (DLAB=0, write).
func (p *Uart) WriteTHR(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadIER reads Interrupt Enable Register (DLAB=0).
func (p *Uart) ReadIER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteIER writes Interrupt Enable Register (DLAB=0).
func (p *Uart) WriteIER(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// WriteFCR writes FIFO Control Register (write). Bit0=enable, Bit1=Rx reset, Bit2=Tx reset.
func (p *Uart) WriteFCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadIIR reads Interrupt Identity Register (read). Bit0=0 means interrupt pending.
func (p *Uart) ReadIIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// ReadLCR reads Line Control Register. Bits[1:0]=word length, bit7=DLAB.
func (p *Uart) ReadLCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteLCR writes Line Control Register. Bits[1:0]=word length, bit7=DLAB.
func (p *Uart) WriteLCR(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMCR reads Modem Control Register.
func (p *Uart) ReadMCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMCR writes Modem Control Register.
func (p *Uart) WriteMCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadLSR reads Line Status Register. Bit0=RxReady, Bit5=TxHoldEmpty, Bit6=TxEmpty.
func (p *Uart) ReadLSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// UartLsr UART Line Status Register.
const (
    // RXREADY Receive data ready.
    UartLsrRXREADYPos = 0
    UartLsrRXREADYMsk = 0x1 << 0
    // TXHOLDEMPTY Transmitter holding register empty. 1=safe to write.
    UartLsrTXHOLDEMPTYPos = 5
    UartLsrTXHOLDEMPTYMsk = 0x1 << 5
    // TXEMPTY Transmitter empty.
    UartLsrTXEMPTYPos = 6
    UartLsrTXEMPTYMsk = 0x1 << 6
)

