// Code generated by chiptool; DO NOT EDIT.

package ast2500

import "github.com/usbarmory/tamago/internal/reg"

// Vic AST2500 VIC interrupt controller. 64 IRQ sources. Legacy block covers IRQ0-31; New Mapping block at +0x80 covers all 64.
type Vic struct {
    Base uintptr
}

// ReadIRQSTATUS reads VIC00 IRQ Status Register (active+enabled, IRQ0-31).
func (p *Vic) ReadIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// ReadFIQSTATUS reads VIC04 FIQ Status Register (IRQ0-31).
func (p *Vic) ReadFIQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// ReadRAWSTATUS reads VIC08 Raw Interrupt Status (pre-mask, IRQ0-31).
func (p *Vic) ReadRAWSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// ReadINTSELECT reads VIC0C Interrupt Selection. 0=IRQ, 1=FIQ (IRQ0-31).
func (p *Vic) ReadINTSELECT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteINTSELECT writes VIC0C Interrupt Selection. 0=IRQ, 1=FIQ (IRQ0-31).
func (p *Vic) WriteINTSELECT(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadINTENABLE reads VIC10 Interrupt Enable (W1S, IRQ0-31). Write 1 to enable.
func (p *Vic) ReadINTENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteINTENABLE writes VIC10 Interrupt Enable (W1S, IRQ0-31). Write 1 to enable.
func (p *Vic) WriteINTENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// WriteINTENCLEAR writes VIC14 Interrupt Enable Clear (W1C, IRQ0-31). Write 1 to disable.
func (p *Vic) WriteINTENCLEAR(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadSOFTINT reads VIC18 Software Interrupt (IRQ0-31).
func (p *Vic) ReadSOFTINT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteSOFTINT writes VIC18 Software Interrupt (IRQ0-31).
func (p *Vic) WriteSOFTINT(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// WriteSOFTINTCLR writes VIC1C Software Interrupt Clear (IRQ0-31).
func (p *Vic) WriteSOFTINTCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// WriteEDGEINTCLR writes VIC38 Edge-triggered Interrupt Clear (IRQ0-31).
func (p *Vic) WriteEDGEINTCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadNEWIRQSTATUSL reads VIC80 New Mapping IRQ Status Low (IRQ0-31).
func (p *Vic) ReadNEWIRQSTATUSL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// ReadNEWIRQSTATUSH reads VIC84 New Mapping IRQ Status High (IRQ32-63).
func (p *Vic) ReadNEWIRQSTATUSH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// ReadNEWINTENABLEL reads VICA0 New Mapping Interrupt Enable Low (W1S, IRQ0-31).
func (p *Vic) ReadNEWINTENABLEL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteNEWINTENABLEL writes VICA0 New Mapping Interrupt Enable Low (W1S, IRQ0-31).
func (p *Vic) WriteNEWINTENABLEL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadNEWINTENABLEH reads VICA4 New Mapping Interrupt Enable High (W1S, IRQ32-63).
func (p *Vic) ReadNEWINTENABLEH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteNEWINTENABLEH writes VICA4 New Mapping Interrupt Enable High (W1S, IRQ32-63).
func (p *Vic) WriteNEWINTENABLEH(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// WriteNEWINTENCLEARL writes VICA8 New Mapping Interrupt Enable Clear Low (W1C, IRQ0-31).
func (p *Vic) WriteNEWINTENCLEARL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// WriteNEWINTENCLEARH writes VICAC New Mapping Interrupt Enable Clear High (W1C, IRQ32-63).
func (p *Vic) WriteNEWINTENCLEARH(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

